### PR TITLE
Reservation wizard started

### PR DESCRIPTION
**Pull request by ryanpoints**

### CODE REVIEW

**Comment by stekza01** [comment]
We're getting a wizard??

**Comment by dhondo01** [comment]
Hahaha!

On Thursday, December 10, 2015, Ryan Bennett <notifications@github.com>
wrote:

>
> <https://camo.githubusercontent.com/b582f937132fa30883d8bfb4618d9295eab91535/687474703a2f2f646174612e77686963646e2e636f6d2f696d616765732f31323139303337392f6c617267652e706e67>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RoomReserve/RoomReserve/pull/36#issuecomment-163788454>
> .
>


-- 

*Dorjee Dhondup*
Computer Science Major | Class of 2016
Luther College, Decorah IA
Website <http://dorjeedhondup.me/>
<https://www.linkedin.com/in/dorjeedhondup>  <https://github.com/dhondo01>
<https://twitter.com/dhondo01>

**Comment by dhondo01** [comment]
Nice haha!

**Pull request merged**
